# Site settings
title: 多文化共生の地域づくり 私にもできることを形にする講座
email: itoshima.mamawriters@gmail.com
url: https://tomonowproject.github.io
description: "異なる文化を持つ人が、地域で快適に生活するために、多文化共生に詳しい専門家のお話やワークショップで楽しく学び、「私にもできること」を考え、形にしていきます。10月～1月まで6回の連続講座。外国語が話せなくても大丈夫。一緒に一歩を踏み出してみませんか？子育て世代も大歓迎♪"
keywords: "多文化, 糸島, 講座, 地域づくり, 異文化, 共生, まちづくり, 外国人, 国際, 国際交流"
skills: "「近所に住む外国の人、気になるけど言葉が通じなかったらどうしよう」「もっと気軽にいろいろ誘えたらな」<br>異なる文化を持つ人が、地域で快適に生活するために、多文化共生に詳しい専門家のお話やワークショップで楽しく学び、「私にもできること」を考え、形にしていきます。10月～1月まで6回の連続講座。外国語が話せなくても大丈夫。一緒に一歩を踏み出してみませんか？子育て世代も大歓迎♪"
meta_author: 糸島ママライターズ「ともなうプロジェクト」実行委員会

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fffbd4
  primary-rgb: "255,251,211"
  secondary: e7bc4a
  secondary-rgb: "231,188,74"
  secondary-dark: d8963b
  tertiary: 6eb3ae
  dark-text: 4a4a4a

# Footer settings
footer:
  copyright: 糸島ママライターズ「ともなうプロジェクト」実行委員会
  location: 会場
  social: お問い合わせ・お申し込み
  credits: 日程・受講料

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: "mailto:itoshima.mamawriters@gmail.com"
    link-text: お問い合わせ
  - title: paper-plane
    url: https://bit.ly/TomoApp
    link-text: お申し込み

# Postal address (add as many lines as necessary)
address:
  - line: 東風コミュニティセンター
  - line:  (旧東風公民館)
  - line: 糸島市潤四丁目10番2号

# Credits content
credits: '　10/7(水)、10/14(水)、10/21(水)、11/4(水)、11/11(水)、1/20(水)<br>10:00~12:00<br>1,000円（全6回分）<br>（10/7の一般公開講座のみの参加は無料）'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
